import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProviders from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | Aroma",
    default: "Create Next App | Aroma",
  },
  description: "Generated by create next app",
  metadataBase: new URL("http://localhost:5000"),
  alternates: {
    canonical: "/",
  },
  creator: "Aroma",
  openGraph: {
    title: "My Practice",
    description: "There is a huge thing going around.",
    url: "http://localhost:5000",
    images: [
      {
        url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fdiscourse.webflow.com%2Ft%2Fopen-graph-issues%2F31370&psig=AOvVaw3RqSzlah_rhtGYKUw-jrv5&ust=1720833740546000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCJiEq7SroIcDFQAAAAAdAAAAABAE",
        width: 600,
        height: 800,
      },
    ],
  },
  icons: {
    icon: "",
  },
};

export default function RootLayout({
  children,
  hasHeader = false,
}: Readonly<{
  children: React.ReactNode;
  hasHeader?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProviders>
          <header>
            <nav>
              <ul>
                <li className="nav-link">Home</li>
                <li className="nav-link">About Us</li>
                <li className="nav-link">Contact</li>
              </ul>
            </nav>
          </header>
          <main>{children}</main>
          <footer>
            <Link href="/">Footer</Link>
          </footer>
        </QueryProviders>
        {/* && is short-circuiting */}
      </body>
    </html>
  );
}
